// Generates src/components/icons.tsx from @material-symbols/svg-400 — Cando's generator
// (`packages/ui/scripts/generate-icons.mjs` there), copied with the console's own glyph list
// (ADR 0017, GRA-44).
//
// Run from apps/web:  pnpm run generate-icons   — then `pnpm run check` from the root so the
// output is Biome-formatted like everything else. The generated file is committed; the package
// is a devDependency because it is only read here, never at runtime.
//
// Why generated components rather than SVG imports: nothing in this repo compiles a .svg into a
// React component (no SVGR, no vite-plugin-svgr), and adding one would put a build step in front
// of the console for one purpose. Embedding the path data needs no tooling anywhere.
//
// Why outlined + `-fill`: the design system's icons are Material Symbols with the Fill axis on,
// weight 400, in the default (outlined) style — Cando verified that against its drawn frames
// (its CAN-305), and the console takes the system as implemented rather than re-deriving it.
// UNFILLED below carries the per-glyph exceptions Cando keeps for the same reason.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const pkgDir = dirname(require.resolve("@material-symbols/svg-400/package.json"));
const outFile = join(dirname(fileURLToPath(import.meta.url)), "../src/components/icons.tsx");

/**
 * The closed set of Material Symbols the console uses, by upstream name. Adding one means adding
 * it here and regenerating — the export name is derived (`smart_toy` → `SmartToyIcon`), so the
 * list is the only thing to maintain.
 *
 * Two groups, kept as one sorted list: the glyphs the console's screens draw today, and the ones
 * Cando's primitives reach for (chevrons, keyboard arrows, `more_horiz`, `unfold_more`, `search`,
 * `menu`, `view_sidebar`, the toast set …), present now so GRA-45 can copy those primitives in
 * without touching this list.
 */
const NAMES = [
  "add",
  "arrow_back",
  "bolt",
  "check",
  "check_circle",
  "chevron_left",
  "chevron_right",
  "close",
  "content_copy",
  "dangerous",
  "delete",
  "description",
  "edit",
  "electrical_services",
  "explore",
  "history",
  "inbox",
  "info",
  "key",
  "keyboard_arrow_down",
  "keyboard_arrow_up",
  "keyboard_double_arrow_left",
  "keyboard_double_arrow_right",
  "language",
  "logout",
  "menu",
  "more_horiz",
  "notifications",
  "open_in_new",
  "power",
  "progress_activity",
  "refresh",
  "schedule",
  "search",
  "settings",
  "smart_toy",
  "unfold_more",
  "view_sidebar",
  "warning",
  "wifi_off",
];

/**
 * Glyphs generated with the Fill axis *off*, by upstream name — the exceptions to the header's
 * outlined-plus-Fill rule. `view_sidebar` is a panel diagram: filled, its main pane is a solid
 * block, where the design system draws the pane empty with the divider and cells visible (the
 * sidebar toggle; Cando's CAN-317). Cando also lists `grid_view`, which the console does not use.
 */
const UNFILLED = new Set(["view_sidebar"]);

const exportName = (name) =>
  `${name
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")}Icon`;

/**
 * Every file in the package is one <svg viewBox="0 -960 960 960"> holding one <path d>. The
 * parse asserts that shape instead of tolerating variations, so an upstream format change
 * fails the regeneration loudly rather than emitting something subtly wrong.
 */
const pathData = (name) => {
  const file = UNFILLED.has(name) ? `${name}.svg` : `${name}-fill.svg`;
  const svg = readFileSync(join(pkgDir, "outlined", file), "utf8").trim();
  const match = svg.match(
    /^<svg xmlns="[^"]*" width="\d+" height="\d+" viewBox="0 -960 960 960"><path d="([^"]+)"\/><\/svg>$/,
  );
  if (!match) throw new Error(`unexpected SVG shape for ${file}`);
  return match[1];
};

const version = require("@material-symbols/svg-400/package.json").version;

const components = NAMES.map(
  (
    name,
  ) => `/** Material Symbols \`${name}\`, ${UNFILLED.has(name) ? "Fill axis off — see UNFILLED in the generator" : "filled"}. */
export function ${exportName(name)}(props: IconProps) {
  return <MaterialSymbol d="${pathData(name)}" {...props} />;
}`,
).join("\n\n");

const output = `// Generated by scripts/generate-icons.mjs from @material-symbols/svg-400@${version} — do not
// edit by hand. Regenerate: \`pnpm run generate-icons\` from apps/web, then \`pnpm run check\` from
// the root. The header comment in that script records why these are generated components and
// why the variant is outlined + Fill (ADR 0017).
import type { SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;

/**
 * lucide-react marked an icon aria-hidden unless the caller supplied a11y props of its own, and
 * every call site was written against that default — reproduced here so the swap to Material
 * Symbols changed no announced semantics (GRA-44, the same finding as Cando's CAN-305).
 */
const hasA11yProp = (props: IconProps) =>
  Object.keys(props).some((key) => key.startsWith("aria-") || key === "role");

function MaterialSymbol({ d, ...props }: IconProps & { d: string }) {
  return (
    // biome-ignore lint/a11y/noSvgWithoutTitle: decorative by default — aria-hidden is spread below unless the caller brings its own a11y props, which the rule cannot see
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 -960 960 960"
      width={24}
      height={24}
      fill="currentColor"
      {...(hasA11yProp(props) ? undefined : { "aria-hidden": true })}
      {...props}
    >
      <path d={d} />
    </svg>
  );
}

${components}
`;

writeFileSync(outFile, output);
console.log(`wrote ${NAMES.length} icons to ${outFile}`);
