/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthShellRouteRouteImport } from './routes/_auth/_shell/route'
import { Route as LinkCallbackRouteImport } from './routes/link.callback'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AuthShellConsentRouteImport } from './routes/_auth/_shell/consent'
import { Route as AuthShellSettingsRouteImport } from './routes/_auth/_shell/settings'
import { Route as AuthPendingIdRouteImport } from './routes/_auth/pending.$id'
import { Route as AuthShellAgentsIndexRouteImport } from './routes/_auth/_shell/agents.index'
import { Route as AuthShellAgentsAgentIdRouteImport } from './routes/_auth/_shell/agents.$agentId'
import { Route as AuthShellConnectionsIndexRouteImport } from './routes/_auth/_shell/connections.index'
import { Route as AuthShellPendingIndexRouteImport } from './routes/_auth/_shell/pending.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShellRouteRoute = AuthShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LinkCallbackRoute = LinkCallbackRouteImport.update({
  id: '/link/callback',
  path: '/link/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthShellConsentRoute = AuthShellConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthShellRouteRoute,
} as any)
const AuthShellSettingsRoute = AuthShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthShellRouteRoute,
} as any)
const AuthPendingIdRoute = AuthPendingIdRouteImport.update({
  id: '/pending/$id',
  path: '/pending/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthShellAgentsIndexRoute = AuthShellAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthShellRouteRoute,
} as any)
const AuthShellAgentsAgentIdRoute = AuthShellAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthShellRouteRoute,
} as any)
const AuthShellConnectionsIndexRoute =
  AuthShellConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AuthShellRouteRoute,
  } as any)
const AuthShellPendingIndexRoute = AuthShellPendingIndexRouteImport.update({
  id: '/pending/',
  path: '/pending/',
  getParentRoute: () => AuthShellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/link/callback': typeof LinkCallbackRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/consent': typeof AuthShellConsentRoute
  '/settings': typeof AuthShellSettingsRoute
  '/pending/$id': typeof AuthPendingIdRoute
  '/agents/$agentId': typeof AuthShellAgentsAgentIdRoute
  '/agents/': typeof AuthShellAgentsIndexRoute
  '/connections/': typeof AuthShellConnectionsIndexRoute
  '/pending/': typeof AuthShellPendingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/link/callback': typeof LinkCallbackRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/consent': typeof AuthShellConsentRoute
  '/settings': typeof AuthShellSettingsRoute
  '/pending/$id': typeof AuthPendingIdRoute
  '/agents/$agentId': typeof AuthShellAgentsAgentIdRoute
  '/agents': typeof AuthShellAgentsIndexRoute
  '/connections': typeof AuthShellConnectionsIndexRoute
  '/pending': typeof AuthShellPendingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_auth/_shell': typeof AuthShellRouteRouteWithChildren
  '/link/callback': typeof LinkCallbackRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_auth/_shell/consent': typeof AuthShellConsentRoute
  '/_auth/_shell/settings': typeof AuthShellSettingsRoute
  '/_auth/pending/$id': typeof AuthPendingIdRoute
  '/_auth/_shell/agents/$agentId': typeof AuthShellAgentsAgentIdRoute
  '/_auth/_shell/agents/': typeof AuthShellAgentsIndexRoute
  '/_auth/_shell/connections/': typeof AuthShellConnectionsIndexRoute
  '/_auth/_shell/pending/': typeof AuthShellPendingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/link/callback'
    | '/oauth/callback'
    | '/consent'
    | '/settings'
    | '/pending/$id'
    | '/agents/$agentId'
    | '/agents/'
    | '/connections/'
    | '/pending/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/link/callback'
    | '/oauth/callback'
    | '/consent'
    | '/settings'
    | '/pending/$id'
    | '/agents/$agentId'
    | '/agents'
    | '/connections'
    | '/pending'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_auth/_shell'
    | '/link/callback'
    | '/oauth/callback'
    | '/_auth/_shell/consent'
    | '/_auth/_shell/settings'
    | '/_auth/pending/$id'
    | '/_auth/_shell/agents/$agentId'
    | '/_auth/_shell/agents/'
    | '/_auth/_shell/connections/'
    | '/_auth/_shell/pending/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LinkCallbackRoute: typeof LinkCallbackRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_shell': {
      id: '/_auth/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthShellRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/link/callback': {
      id: '/link/callback'
      path: '/link/callback'
      fullPath: '/link/callback'
      preLoaderRoute: typeof LinkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_shell/consent': {
      id: '/_auth/_shell/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthShellConsentRouteImport
      parentRoute: typeof AuthShellRouteRoute
    }
    '/_auth/_shell/settings': {
      id: '/_auth/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthShellSettingsRouteImport
      parentRoute: typeof AuthShellRouteRoute
    }
    '/_auth/pending/$id': {
      id: '/_auth/pending/$id'
      path: '/pending/$id'
      fullPath: '/pending/$id'
      preLoaderRoute: typeof AuthPendingIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_shell/agents/': {
      id: '/_auth/_shell/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthShellAgentsIndexRouteImport
      parentRoute: typeof AuthShellRouteRoute
    }
    '/_auth/_shell/agents/$agentId': {
      id: '/_auth/_shell/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthShellAgentsAgentIdRouteImport
      parentRoute: typeof AuthShellRouteRoute
    }
    '/_auth/_shell/connections/': {
      id: '/_auth/_shell/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthShellConnectionsIndexRouteImport
      parentRoute: typeof AuthShellRouteRoute
    }
    '/_auth/_shell/pending/': {
      id: '/_auth/_shell/pending/'
      path: '/pending'
      fullPath: '/pending/'
      preLoaderRoute: typeof AuthShellPendingIndexRouteImport
      parentRoute: typeof AuthShellRouteRoute
    }
  }
}

interface AuthShellRouteRouteChildren {
  AuthShellConsentRoute: typeof AuthShellConsentRoute
  AuthShellSettingsRoute: typeof AuthShellSettingsRoute
  AuthShellAgentsAgentIdRoute: typeof AuthShellAgentsAgentIdRoute
  AuthShellAgentsIndexRoute: typeof AuthShellAgentsIndexRoute
  AuthShellConnectionsIndexRoute: typeof AuthShellConnectionsIndexRoute
  AuthShellPendingIndexRoute: typeof AuthShellPendingIndexRoute
}

const AuthShellRouteRouteChildren: AuthShellRouteRouteChildren = {
  AuthShellConsentRoute: AuthShellConsentRoute,
  AuthShellSettingsRoute: AuthShellSettingsRoute,
  AuthShellAgentsAgentIdRoute: AuthShellAgentsAgentIdRoute,
  AuthShellAgentsIndexRoute: AuthShellAgentsIndexRoute,
  AuthShellConnectionsIndexRoute: AuthShellConnectionsIndexRoute,
  AuthShellPendingIndexRoute: AuthShellPendingIndexRoute,
}

const AuthShellRouteRouteWithChildren = AuthShellRouteRoute._addFileChildren(
  AuthShellRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthShellRouteRoute: typeof AuthShellRouteRouteWithChildren
  AuthPendingIdRoute: typeof AuthPendingIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthShellRouteRoute: AuthShellRouteRouteWithChildren,
  AuthPendingIdRoute: AuthPendingIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LinkCallbackRoute: LinkCallbackRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
