// Generated by scripts/generate-icons.mjs from @material-symbols/svg-400@0.47.2 — do not
// edit by hand. Regenerate: `pnpm run generate-icons` from apps/web, then `pnpm run check` from
// the root. The header comment in that script records why these are generated components and
// why the variant is outlined + Fill (ADR 0017).
import type { SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;

/**
 * lucide-react marked an icon aria-hidden unless the caller supplied a11y props of its own, and
 * every call site was written against that default — reproduced here so the swap to Material
 * Symbols changed no announced semantics (GRA-44, the same finding as Cando's CAN-305).
 */
const hasA11yProp = (props: IconProps) =>
  Object.keys(props).some((key) => key.startsWith("aria-") || key === "role");

function MaterialSymbol({ d, ...props }: IconProps & { d: string }) {
  return (
    // biome-ignore lint/a11y/noSvgWithoutTitle: decorative by default — aria-hidden is spread below unless the caller brings its own a11y props, which the rule cannot see
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 -960 960 960"
      width={24}
      height={24}
      fill="currentColor"
      {...(hasA11yProp(props) ? undefined : { "aria-hidden": true })}
      {...props}
    >
      <path d={d} />
    </svg>
  );
}

/** Material Symbols `add`, filled. */
export function AddIcon(props: IconProps) {
  return (
    <MaterialSymbol d="M450-450H200v-60h250v-250h60v250h250v60H510v250h-60v-250Z" {...props} />
  );
}

/** Material Symbols `arrow_back`, filled. */
export function ArrowBackIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="m274-450 248 248-42 42-320-320 320-320 42 42-248 248h526v60H274Z"
      {...props}
    />
  );
}

/** Material Symbols `bolt`, filled. */
export function BoltIcon(props: IconProps) {
  return <MaterialSymbol d="m320-80 40-280H160l360-520h80l-40 320h240L400-80h-80Z" {...props} />;
}

/** Material Symbols `check`, filled. */
export function CheckIcon(props: IconProps) {
  return <MaterialSymbol d="M378-246 154-470l43-43 181 181 384-384 43 43-427 427Z" {...props} />;
}

/** Material Symbols `check_circle`, filled. */
export function CheckCircleIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="m421-298 283-283-46-45-237 237-120-120-45 45 165 166Zm59 218q-82 0-155-31.5t-127.5-86Q143-252 111.5-325T80-480q0-83 31.5-156t86-127Q252-817 325-848.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 82-31.5 155T763-197.5q-54 54.5-127 86T480-80Z"
      {...props}
    />
  );
}

/** Material Symbols `chevron_left`, filled. */
export function ChevronLeftIcon(props: IconProps) {
  return <MaterialSymbol d="M561-240 320-481l241-241 43 43-198 198 198 198-43 43Z" {...props} />;
}

/** Material Symbols `chevron_right`, filled. */
export function ChevronRightIcon(props: IconProps) {
  return <MaterialSymbol d="M530-481 332-679l43-43 241 241-241 241-43-43 198-198Z" {...props} />;
}

/** Material Symbols `close`, filled. */
export function CloseIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="m249-207-42-42 231-231-231-231 42-42 231 231 231-231 42 42-231 231 231 231-42 42-231-231-231 231Z"
      {...props}
    />
  );
}

/** Material Symbols `content_copy`, filled. */
export function ContentCopyIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M300-200q-24 0-42-18t-18-42v-560q0-24 18-42t42-18h440q24 0 42 18t18 42v560q0 24-18 42t-42 18H300ZM180-80q-24 0-42-18t-18-42v-620h60v620h500v60H180Z"
      {...props}
    />
  );
}

/** Material Symbols `dangerous`, filled. */
export function DangerousIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M330-120 120-330v-300l210-210h300l210 210v300L630-120H330Zm27-195 123-123 123 123 42-42-123-123 123-123-42-42-123 123-123-123-42 42 123 123-123 123 42 42Z"
      {...props}
    />
  );
}

/** Material Symbols `delete`, filled. */
export function DeleteIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M261-120q-24 0-42-18t-18-42v-570h-41v-60h188v-30h264v30h188v60h-41v570q0 24-18 42t-42 18H261Zm106-146h60v-399h-60v399Zm166 0h60v-399h-60v399Z"
      {...props}
    />
  );
}

/** Material Symbols `description`, filled. */
export function DescriptionIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M319-250h322v-60H319v60Zm0-170h322v-60H319v60ZM220-80q-24 0-42-18t-18-42v-680q0-24 18-42t42-18h361l219 219v521q0 24-18 42t-42 18H220Zm331-554h189L551-820v186Z"
      {...props}
    />
  );
}

/** Material Symbols `edit`, filled. */
export function EditIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M120-120v-128l575-574q8-8 19-12.5t23-4.5q11 0 22 4.5t20 12.5l44 44q9 9 13 20t4 22q0 11-4.5 22.5T823-694L248-120H120Zm619-577 40-40-41-41-40 40 41 41Z"
      {...props}
    />
  );
}

/** Material Symbols `electrical_services`, filled. */
export function ElectricalServicesIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M715-360v-60h95q13 0 21.5 8.5T840-390q0 12-8.5 21t-21.5 9h-95Zm0 160v-60h95q13 0 21.5 8.5T840-230q0 12-8.5 21t-21.5 9h-95Zm-155 40q-29 0-49.5-23.5T490-240h-95v-140h95q0-33 20.5-56.5T560-460h125v300H560ZM275-280q-67 0-111-43.5T120-435q0-68 44-111.5T275-590h65q33 0 54-21t21-54q0-33-21-54t-54-21H190q-12 0-21-9t-9-21q0-13 9-21.5t21-8.5h150q58 0 96.5 38.5T475-665q0 58-38.5 96.5T340-530h-65q-42 0-68.5 26T180-435q0 43 26.5 69t68.5 26h90v60h-90Z"
      {...props}
    />
  );
}

/** Material Symbols `explore`, filled. */
export function ExploreIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="m303-303 270-83 83-270-270 83-83 270Zm177-137q-17 0-28.5-11.5T440-480q0-17 11.5-28.5T480-520q17 0 28.5 11.5T520-480q0 17-11.5 28.5T480-440Zm0 360q-82 0-155-31.5t-127.5-86Q143-252 111.5-325T80-480q0-83 31.5-156t86-127Q252-817 325-848.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 82-31.5 155T763-197.5q-54 54.5-127 86T480-80Z"
      {...props}
    />
  );
}

/** Material Symbols `history`, filled. */
export function HistoryIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M477-120q-149 0-253-105.5T120-481h60q0 125 86 213t211 88q127 0 215-89t88-216q0-124-89-209.5T477-780q-68 0-127.5 31T246-667h105v60H142v-208h60v106q52-61 123.5-96T477-840q75 0 141 28t115.5 76.5Q783-687 811.5-622T840-482q0 75-28.5 141t-78 115Q684-177 618-148.5T477-120Zm128-197L451-469v-214h60v189l137 134-43 43Z"
      {...props}
    />
  );
}

/** Material Symbols `inbox`, filled. */
export function InboxIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M180-120q-24 0-42-18t-18-42v-600q0-24 18-42t42-18h600q24 0 42 18t18 42v600q0 24-18 42t-42 18H180Zm374-196.5q33-23.5 56-59.5h170v-404H180v404h170q23 36 56 59.5t74 23.5q41 0 74-23.5Z"
      {...props}
    />
  );
}

/** Material Symbols `info`, filled. */
export function InfoIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M453-280h60v-240h-60v240Zm50.5-323.2q9.5-9.2 9.5-22.8 0-14.45-9.48-24.22-9.48-9.78-23.5-9.78t-23.52 9.78Q447-640.45 447-626q0 13.6 9.48 22.8 9.48 9.2 23.5 9.2t23.52-9.2ZM480.27-80q-82.74 0-155.5-31.5Q252-143 197.5-197.5t-86-127.34Q80-397.68 80-480.5t31.5-155.66Q143-709 197.5-763t127.34-85.5Q397.68-880 480.5-880t155.66 31.5Q709-817 763-763t85.5 127Q880-563 880-480.27q0 82.74-31.5 155.5Q817-252 763-197.68q-54 54.31-127 86Q563-80 480.27-80Z"
      {...props}
    />
  );
}

/** Material Symbols `key`, filled. */
export function KeyIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M371.5-388.5Q409-426 409-480t-37.5-91.5Q334-609 280-609t-91.5 37.5Q151-534 151-480t37.5 91.5Q226-351 280-351t91.5-37.5ZM280-240q-100 0-170-70T40-480q0-100 70-170t170-70q85 0 142.5 46.5T503-555h344l73 73-127 146-103-84-84 84-71-71h-32q-19 75-80.5 121T280-240Z"
      {...props}
    />
  );
}

/** Material Symbols `keyboard_arrow_down`, filled. */
export function KeyboardArrowDownIcon(props: IconProps) {
  return <MaterialSymbol d="M480-344 240-584l43-43 197 197 197-197 43 43-240 240Z" {...props} />;
}

/** Material Symbols `keyboard_arrow_up`, filled. */
export function KeyboardArrowUpIcon(props: IconProps) {
  return <MaterialSymbol d="M480-554 283-357l-43-43 240-240 240 240-43 43-197-197Z" {...props} />;
}

/** Material Symbols `keyboard_double_arrow_left`, filled. */
export function KeyboardDoubleArrowLeftIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M453-241 213-481l240-240 42 42-198 198 198 198-42 42Zm253 0L466-481l240-240 42 42-198 198 198 198-42 42Z"
      {...props}
    />
  );
}

/** Material Symbols `keyboard_double_arrow_right`, filled. */
export function KeyboardDoubleArrowRightIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M411-481 213-679l42-42 240 240-240 240-42-42 198-198Zm253 0L466-679l42-42 240 240-240 240-42-42 198-198Z"
      {...props}
    />
  );
}

/** Material Symbols `language`, filled. */
export function LanguageIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M323-111.5Q250-143 196-197t-85-127.5Q80-398 80-482t31-156.5Q142-711 196-765t127-84.5Q396-880 480-880t157 30.5Q710-819 764-765t85 126.5Q880-566 880-482t-31 157.5Q818-251 764-197t-127 85.5Q564-80 480-80t-157-31.5ZM480-138q35-36 58.5-82.5T577-331H384q14 60 37.5 108t58.5 85Zm-85-12q-25-38-43-82t-30-99H172q38 71 88 111.5T395-150Zm171-1q72-23 129.5-69T788-331H639q-13 54-30.5 98T566-151ZM152-391h159q-3-27-3.5-48.5T307-482q0-25 1-44.5t4-43.5H152q-7 24-9.5 43t-2.5 45q0 26 2.5 46.5T152-391Zm221 0h215q4-31 5-50.5t1-40.5q0-20-1-38.5t-5-49.5H373q-4 31-5 49.5t-1 38.5q0 21 1 40.5t5 50.5Zm275 0h160q7-24 9.5-44.5T820-482q0-26-2.5-45t-9.5-43H649q3 35 4 53.5t1 34.5q0 22-1.5 41.5T648-391Zm-10-239h150q-33-69-90.5-115T565-810q25 37 42.5 80T638-630Zm-254 0h194q-11-53-37-102.5T480-820q-32 27-54 71t-42 119Zm-212 0h151q11-54 28-96.5t43-82.5q-75 19-131 64t-91 115Z"
      {...props}
    />
  );
}

/** Material Symbols `logout`, filled. */
export function LogoutIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M180-120q-24 0-42-18t-18-42v-600q0-24 18-42t42-18h299v60H180v600h299v60H180Zm486-185-43-43 102-102H360v-60h363L621-612l43-43 176 176-174 174Z"
      {...props}
    />
  );
}

/** Material Symbols `menu`, filled. */
export function MenuIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M120-240v-60h720v60H120Zm0-210v-60h720v60H120Zm0-210v-60h720v60H120Z"
      {...props}
    />
  );
}

/** Material Symbols `more_horiz`, filled. */
export function MoreHorizIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M207.86-432Q188-432 174-446.14t-14-34Q160-500 174.14-514t34-14Q228-528 242-513.86t14 34Q256-460 241.86-446t-34 14Zm272 0Q460-432 446-446.14t-14-34Q432-500 446.14-514t34-14Q500-528 514-513.86t14 34Q528-460 513.86-446t-34 14Zm272 0Q732-432 718-446.14t-14-34Q704-500 718.14-514t34-14Q772-528 786-513.86t14 34Q800-460 785.86-446t-34 14Z"
      {...props}
    />
  );
}

/** Material Symbols `notifications`, filled. */
export function NotificationsIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M160-200v-60h80v-304q0-84 49.5-150.5T420-798v-22q0-25 17.5-42.5T480-880q25 0 42.5 17.5T540-820v22q81 17 130.5 83.5T720-564v304h80v60H160ZM480-80q-33 0-56.5-23.5T400-160h160q0 33-23.5 56.5T480-80Z"
      {...props}
    />
  );
}

/** Material Symbols `open_in_new`, filled. */
export function OpenInNewIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M180-120q-24 0-42-18t-18-42v-600q0-24 18-42t42-18h279v60H180v600h600v-279h60v279q0 24-18 42t-42 18H180Zm202-219-42-43 398-398H519v-60h321v321h-60v-218L382-339Z"
      {...props}
    />
  );
}

/** Material Symbols `power`, filled. */
export function PowerIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M382-120v-118L240-394v-215q0-25 17.5-42.5T300-669h72l-30 30v-201h60v171h156v-171h60v201l-30-30h72q25 0 42.5 17.5T720-609v215L578-238v118H382Z"
      {...props}
    />
  );
}

/** Material Symbols `progress_activity`, filled. */
export function ProgressActivityIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M323-111q-73-31-127-85t-85-127q-31-73-31-157t31-157q31-73 85-127t127-85q73-31 157-31 12 0 21 9t9 21q0 12-9 21t-21 9q-141 0-240.5 99.5T140-480q0 141 99.5 240.5T480-140q141 0 240.5-99.5T820-480q0-12 9-21t21-9q12 0 21 9t9 21q0 84-31 157t-85 127q-54 54-127 85T480-80q-84 0-157-31Z"
      {...props}
    />
  );
}

/** Material Symbols `refresh`, filled. */
export function RefreshIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M480-160q-133 0-226.5-93.5T160-480q0-133 93.5-226.5T480-800q85 0 149 34.5T740-671v-129h60v254H546v-60h168q-38-60-97-97t-137-37q-109 0-184.5 75.5T220-480q0 109 75.5 184.5T480-220q83 0 152-47.5T728-393h62q-29 105-115 169t-195 64Z"
      {...props}
    />
  );
}

/** Material Symbols `schedule`, filled. */
export function ScheduleIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="m627-287 45-45-159-160v-201h-60v225l174 181ZM480-80q-82 0-155-31.5t-127.5-86Q143-252 111.5-325T80-480q0-82 31.5-155t86-127.5Q252-817 325-848.5T480-880q82 0 155 31.5t127.5 86Q817-708 848.5-635T880-480q0 82-31.5 155t-86 127.5Q708-143 635-111.5T480-80Z"
      {...props}
    />
  );
}

/** Material Symbols `search`, filled. */
export function SearchIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M796-121 533-384q-30 26-70 40.5T378-329q-108 0-183-75t-75-181q0-106 75-181t182-75q106 0 180.5 75T632-585q0 43-14 83t-42 75l264 262-44 44ZM377-389q81 0 138-57.5T572-585q0-81-57-138.5T377-781q-82 0-139.5 57.5T180-585q0 81 57.5 138.5T377-389Z"
      {...props}
    />
  );
}

/** Material Symbols `settings`, filled. */
export function SettingsIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="m388-80-20-126q-19-7-40-19t-37-25l-118 54-93-164 108-79q-2-9-2.5-20.5T185-480q0-9 .5-20.5T188-521L80-600l93-164 118 54q16-13 37-25t40-18l20-127h184l20 126q19 7 40.5 18.5T669-710l118-54 93 164-108 77q2 10 2.5 21.5t.5 21.5q0 10-.5 21t-2.5 21l108 78-93 164-118-54q-16 13-36.5 25.5T592-206L572-80H388Zm92-270q54 0 92-38t38-92q0-54-38-92t-92-38q-54 0-92 38t-38 92q0 54 38 92t92 38Z"
      {...props}
    />
  );
}

/** Material Symbols `smart_toy`, filled. */
export function SmartToyIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M147-376q-45 0-76-31.21T40-483q0-44.58 31.21-75.79Q102.42-590 147-590v-123q0-24 18-42t42-18h166q0-45 31-76t76-31q45 0 76 31.21T587-773h166q24 0 42 18t18 42v123q45 0 76 31.21T920-483q0 44.58-31.21 75.79Q857.58-376 813-376v196q0 24-18 42t-42 18H207q-24 0-42-18t-18-42v-196Zm224.5-111.74q11.5-11.73 11.5-28.5 0-16.76-11.74-28.26-11.73-11.5-28.5-11.5-16.76 0-28.26 11.74-11.5 11.73-11.5 28.5 0 16.76 11.74 28.26 11.73 11.5 28.5 11.5 16.76 0 28.26-11.74Zm274 0q11.5-11.73 11.5-28.5 0-16.76-11.74-28.26-11.73-11.5-28.5-11.5-16.76 0-28.26 11.74-11.5 11.73-11.5 28.5 0 16.76 11.74 28.26 11.73 11.5 28.5 11.5 16.76 0 28.26-11.74ZM312-285h336v-60H312v60Z"
      {...props}
    />
  );
}

/** Material Symbols `unfold_more`, filled. */
export function UnfoldMoreIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M480-120 300-300l44-44 136 136 136-136 44 44-180 180ZM344-612l-44-44 180-180 180 180-44 44-136-136-136 136Z"
      {...props}
    />
  );
}

/** Material Symbols `view_sidebar`, Fill axis off — see UNFILLED in the generator. */
export function ViewSidebarIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="M140-160q-24.75 0-42.37-17.63Q80-195.25 80-220v-520q0-24.75 17.63-42.38Q115.25-800 140-800h680q24.75 0 42.38 17.62Q880-764.75 880-740v520q0 24.75-17.62 42.37Q844.75-160 820-160H140Zm543-443h137v-137H683v137Zm0 186h137v-126H683v126ZM140-220h483v-520H140v520Zm543 0h137v-137H683v137Z"
      {...props}
    />
  );
}

/** Material Symbols `warning`, filled. */
export function WarningIcon(props: IconProps) {
  return (
    <MaterialSymbol
      d="m40-120 440-760 440 760H40Zm465.5-125.68q8.5-8.67 8.5-21.5 0-12.82-8.68-21.32-8.67-8.5-21.5-8.5-12.82 0-21.32 8.68-8.5 8.67-8.5 21.5 0 12.82 8.68 21.32 8.67 8.5 21.5 8.5 12.82 0 21.32-8.68ZM454-348h60v-224h-60v224Z"
      {...props}
    />
  );
}
