/**
 * `@graft/core` — persons, agents, connections, the toolbox, the working set, approvals, pending
 * actions, `acquire` jobs and the ledger (GRA-1, "The core and its seams"), as services with
 * injected dependencies that run without a database. The `*.deps.ts` beside each service binds the
 * real repositories; a test passes fakes.
 */

export { type AcquireJobDeps, defaultAcquireJobDeps } from "./acquire-job/acquire-job.deps";
export {
  type AppendAcquireTraceInput,
  appendAcquireJobProgress,
  appendAcquireTrace,
  claimRunnableAcquireJobs,
  completeAcquireJob,
  createAcquireJob,
  type FinishAcquireAttemptInput,
  finishAcquireAttempt,
  GOAL_MAX_LENGTH,
  getAcquireJob,
  HINTS_MAX_LENGTH,
  heartbeatAcquireJob,
  listAcquireAttempts,
  listAcquireJobs,
  listAcquireTraces,
  recordAcquireJobAttempt,
  recordAcquireJobTokens,
  type StartAcquireAttemptInput,
  startAcquireAttempt,
  startAcquireJob,
  TRACE_READ_LIMIT,
  TRACE_TEXT_MAX_LENGTH,
} from "./acquire-job/acquire-job.service";
export {
  GENERIC_SECRET_FIELD_NAMES,
  MIN_SECRET_LENGTH,
  REDACTED,
  type RedactionRule,
  redactText,
  redactValue,
  secretFieldNamesFor,
} from "./acquire-job/redaction";
export { type AgentDeps, defaultAgentDeps } from "./agent/agent.deps";
export {
  type ActiveAgentScope,
  AGENT_NAME_MAX_LENGTH,
  type AgentConnectedViaOutput,
  type AgentLimitsPatch,
  type AgentListOutput,
  type AgentOutput,
  type AgentScopeMode,
  addConnectionToAgentScope,
  type CreateAgentForClientInput,
  type CreateAgentInput,
  connectExistingAgentToClient,
  createAgent,
  createAgentForClient,
  getAgent,
  getAgentScope,
  IDLE_WINDOW_DAYS_RANGE,
  listActiveAgentScopes,
  listAgents,
  revokeAgent,
  type SetAgentScopeInput,
  setAgentScope,
  toAgentOutput,
  updateAgentLimits,
  WORKING_SET_CAP_RANGE,
} from "./agent/agent.service";
export {
  type ApprovalState,
  type ApprovalVerdict,
  approvalDecision,
  type ToolAnnotations,
} from "./approval/approval.decision";
export { type ApprovalDeps, defaultApprovalDeps } from "./approval/approval.deps";
export {
  decideToolCall,
  getApproval,
  getBuildApproval,
  grantBuildApproval,
  listApprovals,
  revokeApproval,
  setApproval,
  setAskEveryCall,
} from "./approval/approval.service";
export { type BlobDeps, defaultBlobDeps } from "./blob/blob.deps";
export {
  type BlobWrittenInput,
  getBlob,
  getBlobs,
  listBlobs,
  liveBlobBytes,
  recordBlobsWritten,
} from "./blob/blob.service";
export {
  ASK_ANSWERED_MESSAGE_TYPE,
  type AskAnsweredMessage,
  askAnsweredMessage,
  FROM_CARD,
  FROM_CARD_CLOSE_MS,
  FROM_CARD_PARAM,
  openedFromCard,
} from "./connection/card.rules";
export { type ConnectionDeps, createConnectionDeps } from "./connection/connection.deps";
export {
  DISPLAY_NAME_MAX_LENGTH,
  HOST_NOT_PUBLIC,
  type HostSetRefusal,
  type HostSetVerdict,
  SCHEME_PARAMETERS,
  SIGN_IN_HOSTS,
  type SignInHostsVerdict,
  setAsideSignInHosts,
  takesCredential,
  VENDOR_MAX_LENGTH,
  validateCredentialFields,
  validateDisplayName,
  validateHostSet,
  validateIssuedCredentialFields,
  validateSchemeConfig,
  validateVendor,
} from "./connection/connection.rules";
export {
  type ConnectionOutput,
  type ConnectThroughProviderInput,
  completeOAuthConsent,
  connectThroughProvider,
  getConnection,
  isConnectionUsable,
  listConnections,
  markOAuthConsentRequired,
  type ProviderRelease,
  type RegisterConnectionInput,
  type RegisterConnectionWithCredentialInput,
  type RegisterProviderConnectionInput,
  type RevokeConnectionResult,
  reconnectConnection,
  registerConnection,
  registerConnectionWithCredential,
  registerProviderConnection,
  retryProviderRelease,
  revokeConnection,
  type StartedOAuthConsent,
  type StartOAuthConsentInput,
  setConnectionCredential,
  startOAuthConsent,
  storeRefreshedCredential,
  toConnectionOutput,
  toProxyConnection,
  widenKeylessConnectionHosts,
  widenProviderConnectionHosts,
} from "./connection/connection.service";
export {
  createGatewayProvider,
  GATEWAY_PROVIDER,
  type GatewayProviderConfig,
  gatewayCovers,
  gatewayCoversHost,
} from "./connection/gateway-provider";
export {
  LINK_CALLBACK_MESSAGE_TYPE,
  LINK_CALLBACK_PATH,
  LINK_CALLBACK_STATUSES,
  LINK_CHANNEL,
  LINK_CONSOLE_CALLBACK_PATH,
  LINK_OUTCOME_PARAM,
  LINK_STATE_PARAM,
  type LinkCallbackMessage,
  type LinkCallbackOutcome,
  type LinkCallbackStatus,
  linkCallbackMessage,
  linkCallbackRedirect,
  linkCallbackUri,
  readLinkCallbackSearch,
} from "./connection/link.rules";

export {
  LINK_STATE_TTL_MS,
  type LinkStatePayload,
  type LinkStateVerdict,
  signLinkState,
  verifyLinkState,
} from "./connection/link-state";
export {
  GOOGLE_TESTING_MODE_NOTICE,
  hasGoogleHost,
  isGoogleHost,
  isOAuthAuthorizationCode,
  OAUTH_AUTHORIZATION_CODE,
  OAUTH_CALLBACK_MESSAGE_TYPE,
  OAUTH_CALLBACK_PATH,
  OAUTH_CALLBACK_STATUSES,
  OAUTH_CONSENT_CHANNEL,
  OAUTH_CONSOLE_CALLBACK_PATH,
  type OAuthCallbackMessage,
  type OAuthCallbackOutcome,
  type OAuthCallbackStatus,
  type OAuthPublicState,
  type OAuthState,
  type OAuthStatus,
  oauthCallbackMessage,
  oauthCallbackRedirect,
  oauthPublicState,
  oauthRedirectUri,
  readOAuthCallbackSearch,
  readOAuthState,
} from "./connection/oauth.rules";
export {
  buildAuthorizeUrl,
  generatePkce,
  OAUTH_STATE_TTL_MS,
  type OAuthStatePayload,
  type OAuthStateVerdict,
  pkceChallenge,
  signOAuthState,
  verifyOAuthState,
} from "./connection/oauth-consent";
export {
  type ConnectionProvider,
  DEFAULT_PROVIDERS,
  describeProviders,
  KEYRING_PROVIDER,
  keyringProvider,
  type ProviderConnect,
  type ProviderConnectDescription,
  type ProviderConnectionRow,
  type ProviderDescription,
  type ProviderLink,
  type ProviderLinkComplete,
  type ProviderLinkOutcome,
  type ProviderLinkStart,
  type ProviderLinkStarted,
  type ProviderResolution,
  providerFor,
  providerLinkOf,
  providerListProblem,
  providerNamed,
} from "./connection/provider";
export type { ServiceContext } from "./context";
export {
  HTTP_STATUS_BY_CODE,
  isUniqueViolation,
  orNotFound,
  ServiceError,
  type ServiceErrorCode,
} from "./errors";
export { isKebabCase } from "./kebab-case";
export { defaultLedgerDeps, type LedgerDeps } from "./ledger/ledger.deps";
export {
  lastUsedAtByTool,
  listUsage,
  listVendorUsage,
  recordUsage,
  type UsageInput,
  type VendorUsageRow,
} from "./ledger/ledger.service";
export { defaultMcpOAuthDeps, type McpOAuthDeps } from "./mcp-oauth/mcp-oauth.deps";
export { openRotationReplay, sealRotationReplay } from "./mcp-oauth/mcp-oauth.replay";
export {
  AUTHORIZATION_REQUEST_PARAM_NAMES,
  AUTHORIZATION_SERVER_METADATA_PATH,
  type AuthorizationRequestParamName,
  type AuthorizationRequestParams,
  authorizationRequestSearch,
  clientRedirect,
  isAllowedRedirectUri,
  isValidCodeChallenge,
  isValidCodeVerifier,
  MCP_CONSENT_PATH,
  MCP_ENDPOINT_PATH,
  MCP_OAUTH_PATHS,
  mcpConsentUrl,
  mcpIssuer,
  mcpResourceUrl,
  PROTECTED_RESOURCE_METADATA_PATH,
  protectedResourceMetadataUrl,
  readAuthorizationRequestParams,
  redirectTargetOf,
  sameResource,
} from "./mcp-oauth/mcp-oauth.rules";
export {
  type AuthorizationRefusalReason,
  type AuthorizationVerdict,
  authenticateClient,
  authorizationErrorRedirect,
  authorizationServerMetadata,
  type ClientRegistration,
  type ClientRegistrationResponse,
  type ConsentDecision,
  type ConsentOutcome,
  decideConsent,
  describeClient,
  exchangeAuthorizationCode,
  grantTokens,
  judgeAuthorizationRequest,
  MCP_ACCESS_TOKEN_TTL_SECONDS,
  MCP_AUTHORIZATION_CODE_TTL_SECONDS,
  MCP_CLIENT_NAME_MAX_LENGTH,
  MCP_CLIENT_NAME_PLACEHOLDER,
  MCP_MAX_REDIRECT_URIS,
  MCP_METADATA_PATHS,
  MCP_REDIRECT_URI_MAX_LENGTH,
  MCP_REFRESH_GRACE_SECONDS,
  MCP_REGISTRATION_MAX_BYTES,
  type McpClientDescription,
  type McpOAuthConfig,
  OAuthProtocolError,
  type PresentedClientCredentials,
  protectedResourceMetadata,
  refreshTokens,
  registerMcpClient,
  revokeToken,
  type TokenResponse,
  type ValidAuthorizationRequest,
  validateAuthorizationRequest,
  validateClientRegistration,
} from "./mcp-oauth/mcp-oauth.service";
export { createModelKeyDeps, type ModelKeyDeps } from "./model-key/model-key.deps";
export {
  deletePersonModelKey,
  findPersonModelKeyRow,
  getPersonModelKey,
  MODEL_ID_MAX_LENGTH,
  MODEL_KEY_FIELD,
  MODEL_KEY_MAX_LENGTH,
  MODEL_KEY_SCOPE,
  type ModelKeyOutput,
  modelKeyScope,
  type SetModelKeyInput,
  setPersonModelKey,
  toModelKeyOutput,
} from "./model-key/model-key.service";
export {
  defaultPendingActionDeps,
  type PendingActionDeps,
} from "./pending-action/pending-action.deps";
export {
  answerPendingAction,
  type CreatePendingActionInput,
  consumePendingAction,
  createPendingAction,
  DEFAULT_PENDING_ACTION_TTL_MS,
  getPendingAction,
  getPendingActionForPerson,
  listOpenPendingActions,
  MAX_PENDING_ACTION_TTL_MS,
} from "./pending-action/pending-action.service";
export {
  AGENT_TOKEN_DISPLAY_LENGTH,
  AGENT_TOKEN_PREFIX,
  type AgentScope,
  type AgentTokenDeps,
  type AgentTokenRefusal,
  bearerTokenFrom,
  hashAgentToken,
  MCP_ACCESS_TOKEN_PREFIX,
  MCP_AUTHORIZATION_CODE_PREFIX,
  MCP_CLIENT_SECRET_PREFIX,
  MCP_REFRESH_TOKEN_PREFIX,
  type MintedAgentToken,
  mintAgentToken,
  mintOpaqueToken,
  type OpaqueToken,
  type Principal,
  requireAgent,
  requirePerson,
  type SessionLike,
} from "./tenancy";
export { defaultToolDeps, type ToolDeps } from "./tool/tool.deps";
export {
  activateToolVersion,
  addToolVersion,
  type CreateToolInput,
  createTool,
  getToolById,
  getToolByName,
  getToolVersion,
  listTools,
  listToolVersions,
  moveToolPointer,
  nextVersionNumber,
  publishToolVersion,
  rebindToolIfConnectionDead,
  recordDryRun,
  TOOL_DESCRIPTION_MAX_LENGTH,
  TOOL_NAME_MAX_LENGTH,
  type ToolDefinitionPatch,
  type ToolVersionInput,
  updateToolDefinition,
  validateToolDefinition,
} from "./tool/tool.service";
export {
  DAY_MS,
  type SweepCause,
  type SweepDecision,
  type SweepDecisionInput,
  type SweepDemotion,
  type SweepEntry,
  sweepDecision,
} from "./working-set/sweep.decision";
export { defaultWorkingSetDeps, type WorkingSetDeps } from "./working-set/working-set.deps";
export {
  countWorkingSet,
  demoteTool,
  isPromoted,
  listWorkingSet,
  listWorkingSetChanges,
  promoteTool,
  touchToolUsed,
  type WorkingSetChange,
} from "./working-set/working-set.service";
